const { createObject } = require('../../utils');

module.exports = createObject([
  'FIRST_CONTENTFUL_PAINT',
  'LOAD_TIME',
  'LIGHTHOUSE_ACCESIBILITY_OVERALL',
  'LIGHTHOUSE_SEO_OVERALL',
  'LIGHTHOUSE_PWA_OVERALL',
  'LIGHTHOUSE_PERFORMANCE_OVERALL',
  'LIGHTHOUSE_BEST_PRACTICES_OVERALL',
  'TIME_TO_INTERACTIVE'
]);
