const { createObject } = require('../../utils');

module.exports = createObject([
  'FIRST_CONTENTFUL_PAINT',
  'FIRST_MEANINGFUL_PAINT',
  'LIGHTHOUSE_ACCESIBILITY_OVERALL',
  'LIGHTHOUSE_SEO_OVERALL',
  'LIGHTHOUSE_PWA_OVERALL',
  'LIGHTHOUSE_PERFORMANCE_OVERALL',
  'LIGHTHOUSE_BEST_PRACTICES_OVERALL'
]);
